routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/migrate-fresh', function () {
    
    Artisan::call('migrate:fresh');
    
    Artisan::call('db:seed');
    
    Artisan::call('config:cache');
    
    Artisan::call('config:clear');
    
    Artisan::call('cache:clear');
    
    Artisan::call('route:clear');
    
    Artisan::call('view:clear');
    
    Artisan::call('clear-compiled');
    
    return "OK.";
});

Route::get('/clear-cache', function () {
    
    Artisan::call('config:cache');
    
    Artisan::call('config:clear');
    
    Artisan::call('cache:clear');
    
    Artisan::call('route:clear');
    
    Artisan::call('view:clear');
    
    Artisan::call('clear-compiled');
    
    return "OK.";
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/conversation', 'ConversationController@index')->name('conversation.index');

Route::get('/conversation/{user}', 'ConversationController@index')->name('conversation.show');

app/Http/Controllers/Api/ConversationsController.php
<?php
/**
 * Created by PhpStorm.
 * User: leinad
 * Date: 10/17/18
 * Time: 2:47 PM
 */

namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;
use App\Http\Resources\MessageResource;
use App\Http\Resources\UserResource;
use App\Models\Message;
use App\Models\User;
use Illuminate\Http\Request;

class ConversationsController extends Controller
{
    function users(Request $request)
    {
        $users = User::withCount([
            "messagesWhereFrom" => function ($query) use ($request) {
                return $query->whereNull('read_at')->whereToId($request->user()->id);
            }
        ])->where('id', '!=', $request->user()->id)->get(['id', 'name', 'slug']);
        
        return response()->json([
            'conversationUsers' => UserResource::collection($users),
            'currentUser' => new UserResource($request->user())
        ]);
    }
    
    function messages(Request $request, User $user)
    {
        $messages = Message::whereIn('from_id', [$request->user()->id, $user->id])
            ->whereIn('to_id', [$request->user()->id, $user->id])
            ->orderBy('created_at')
            ->get();
        
        return response()->json(['conversationMessages' => MessageResource::collection($messages)]);
    }
    
    function sendMessages(Request $request, User $user)
    {
        $validator = validator($request->all(), ['content' => 'required|string']);
        if ($validator->fails()) {
            return response()->json(['message' => join(" ", $validator->errors()->get('content'))], 400);
        }
        
        /** @var User $authUser */
        $authUser = $request->user();
        $message = $authUser->messagesWhereFrom()->create([
            'content' => $request->input('content'),
            'to_id' => $user->id
        ]);
        
        return response()->json(['message' => new MessageResource($message)]);
    }
}

app/Http/Controllers/ConversationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;

class ConversationController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
//        $users = $this->getOtherUsers();
        
        return view('conversations.index', compact('users'));
    }
    
    public function show(User $user)
    {
        $messages = Message::whereIn('from_id', [auth()->id(), $user->id])
            ->whereIn('to_id', [auth()->id(), $user->id])
            ->orderBy('created_at')
            ->get();
        
        $unReadMessages = $messages->where('read_at', '=', null)
            ->where('to_id', "=", auth()->id())
            ->map(function ($message) {
                return $message->id;
            });
        
        if ($unReadMessages->isNotEmpty()) {
            Message::whereIn('id', $unReadMessages->toArray())->update(['read_at' => now()]);
        }
        
        $users = $this->getOtherUsers();
        
        return view('conversations.show', compact('users', 'user', 'messages'));
    }
    
    public function store(Request $request, User $user)
    {
        $validator = validator($request->all(), ['content' => 'required|string']);
        if ($validator->fails()) {
            return back()->with($validator)->withInput();
        }
        
        /** @var User $authUser */
        $authUser = auth()->user();
        $authUser->messagesWhereFrom()->create([
            'content' => $request->input('content'),
            'to_id' => $user->id
        ]);
        
        return redirect(route('conversation.show', $user));
    }
    
    private function getOtherUsers(): Collection
    {
        $users = User::withCount([
            "messagesWhereFrom" => function ($query) {
                return $query->whereNull('read_at')->whereToId(auth()->id());
            }
        ])->where('id', '!=', auth()->id())->get(['id', 'name', 'slug']);
        
        return $users;
    }
}

resources/views/conversations/_users.blade.php
<div class="card">
    <div class="card-header">Users</div>
    <div class="card-body">
        <div class="list-group">
            @foreach($users as $user)
                <a href="{{ route('conversation.show', $user) }}#textarea"
                   class="list-group-item">{{ $user->name }}

                    @if($user->messages_where_from_count)
                        <span class="badge badge-pill badge-success">
                            {{ $user->messages_where_from_count }}
                        </span>
                    @endif
                </a>
            @endforeach
        </div>
    </div>
</div>

resources/views/conversations/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <conversation-users></conversation-users>
            </div>

            <div class="col-md-9">
                <router-view></router-view>
            </div>
        </div>
    </div>
@endsection

resources/views/conversations/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                @include('conversations._users', ['users' => $users])
            </div>

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header"><strong>{{ $user->name }}</strong></div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @php
                            $previousDate = now();
                        @endphp

                        @foreach($messages as $message)
                            @if($message->created_at->diffInDays($previousDate) !== 0)

                                @if($message->created_at->diffInDays(now()) == 0)
                                    <p style="text-align: center;">
                                        <strong>Today</strong>
                                    </p>
                                @elseif($message->created_at->diffInDays(now()) == 1)
                                    <p style="text-align: center;">
                                        <strong>Yesterday</strong>
                                    </p>
                                @else
                                    <p style="text-align: center;">
                                        <strong>{{ $message->created_at->format('F d') }}</strong>
                                    </p>
                                @endif

                                @php
                                    $previousDate = $message->created_at;
                                @endphp
                            @endif

                            <div class="row">
                                <div class="col-sm-10 {{ $message->from_id === auth()->id() ? 'offset-sm-2 text-right' : null }}">
                                    <p>
                                        <strong>{!! nl2br(e($message->content)) !!}</strong> <span
                                                style="font-size: 13px">{{ $message->created_at->format('H:i') }}</span>
                                    </p>
                                </div>
                            </div>

                            @if(!$loop->last)
                                <hr>
                            @endif
                        @endforeach
                        <br>

                        <form action="{{ route('conversation.store', $user) }}" method="post">
                            {{ csrf_field() }}

                            <div class="form-group" id="textarea">
                                <textarea name="content" class="form-control" required></textarea>
                            </div>

                            <button class="btn btn-light btn-lg" type="submit">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection